on skript load:
	delete {messages::*}
	add "&7Wil je in een Attractie of is een Attractie Gesloten? &aVraag&7 dan aan een &9Medewerker&7 om hem te openen!" to {messages::*}
	add "&7Je rekening bekijken? &9/money&7!" to {messages::*}
	add "&7Elke dag de watershow: &9Aque FiveCraftia&7! om 12:00 & 20:00, Zien we jou daar?" to {messages::*}
	add "&7Abonneer nu op on &cYoutube &7kanaal! https://www.youtube.com/fivecraft" to {messages::*}
	add "&7Gebruik &9/muziek voor een optimale beleving bij attracties, gebieden en evenementen!" to {messages::*}
	add "&7Zit je vast in de map? Doe &9/spawn&7 of warp naar een andere attractie!	!" to {messages::*}
	

on join:
	set slot 8 of player to player's skull named "&6&lFiveCraft Menu"

on right click:
	if name of item contains "FiveCraft Menu":
		cancel event
		if player has permission "medewerker" or "crew":
			open chest with 2 rows named "&0            |&6&lFiveCraft&0|" to player
		else:
			open chest with 1 rows named "&0            |&6&lFiveCraft&0|" to player
		wait 2 ticks
		set {_x} to {saldo.%uuid of player%}
		format slot 0 of player with 1 of minecart_item named "&a&lAttractie Lijst" with lore "&7&oKlik hier voor alle attracties!" to run [openMenu(player, "status", "")]
		format slot 2 of player with 1 of jukebox named "&9&lAudio Client" with lore "&7&oGebruik voor de complete ervaring!" to close then run [make player execute "/audio"]
		format slot 4 of player with 1 of gold ingot named "&6&lMijn Rekening" with lore "&7&oJe hebt: &2%{_x}% Euro" to be unstealable
		format slot 6 of player with 1 of painting named "&4&lOnder Constructie" with lore "&c&oGeen Toegang!" to be unstealable
		format slot 8 of player with 1 of barrier named "&c&lSluit Menu" with lore "&7&oKlik hier om het menu aftesluiten!" to close
		if player has permission "crew":
			format slot 13 of player with 1 of bedrock named "&3&lAdmin menu" with lore "&7&oVoor de handige functies!" to run [openMenu(player, "admin", "")]
function chat(t: text, p: player):
	if {_t} is "true":
		send "&7[&6FiveCraft&7] De chat is nu &aAangezet&7!" to all players
		set {FC.chat} to true
		openMenu({_p}, "admin")
	else:
		send "&7[&6FiveCraft&7] De chat is nu &cUitgezet&7!" to all players
		set {FC.chat} to false
		openMenu({_p}, "admin")
function clearChat(p: player):
	loop 300 times:
		send "" to all players
	send "&7[&6FiveCraft&7] De chat is opgeschoond!" to all players
function openMenu(p: player, m: text, d: text):
	if {_m} is "admin":
		open chest with 5 rows named "&6&lAdmin Menu" to {_p}
		wait 2 ticks
		if {FC.chat} is true:
			format slot 0 of {_p} with 1 of note block named "&2&lChat in/uitschakelen" with lore "&2Ingeschakeld" to run [chat("false", {_p})]
		else:
			format slot 0 of {_p} with 1 of note block named "&c&lChat in/uitschakelen" with lore "&cUitgeschakeld" to run [chat("true", {_p})]
		format slot 1 of {_p} with 1 of redstone block named "&6&lClear Chat" to run [clearChat({_p})]
		set {_1} to 8
		loop 9 times:
			add 1 to {_1}
			format slot {_1} of {_p} with 1 of black glass named "&7" to be unstealable
		set {_1} to 17
		loop all players:
			add 1 to {_1}
			format slot {_1} of {_p} with loop-player's skull named "&9%loop-value%" to run [openMenu({_p}, "padmin", "%loop-value%")]
	if {_m} is "padmin":
		set {_d} to {_d} parsed as a player
		if {_d} has permission "crew":
			open chest with 1 rows named "&c&lVerboden Toegang" to {_p}
			set {_1} to 0
			loop 9 times:
				format slot {_1} of {_p} with barrier named "&4&lJij hebt geen toegang tot deze speler" with lore "&7Klik hier om terug te gaan!" to run [openMenu({_p}, "admin", "")]
				add 1 to {_1}
		open chest with 1 rows named "&9 %{_d}%" to {_p}
		wait 2 ticks
		format slot 2 of {_p} with 1 of leather boots named "&c&lKick speler" with lore "&7Klik hier om deze player te kicken" to run [kick {_d} due to "&6&lFiveCraft&7>> Jij bent uit de server gezet!"]
		format slot 6 of {_p} with 1 of iron sword named "&4&lBan speler" with lore "&7Klik hier om deze speler te verbannen" to run [execute console command "/ban %{_d}%"]
	if {_m} is "status":
		open chest with 6 rows named "&0            |&a&lStatusMenu&0|" to {_p}
		wait 2 ticks
		set {_1} to 0
		loop 9 times:
			format slot {_1} of {_p} with green glass named "&7" to be unstealable
			add 1 to {_1}
		set {_1} to 45
		loop 9 times:
			format slot {_1} of {_p} with green glass named "&7" to be unstealable
			add 1 to {_1}
			
		set {_1} to 9			
		loop {rides::*}:

			set {_mcapi.title} to loop-value
			set {_mcapi.status} to {ride.%loop-value%}
			replace all "_" with " " in {_mcapi.title}
			if {_mcapi.status} is "automatisch":
				format slot {_1} of {_p} with 1 of blue clay named "&9%{_mcapi.title}%" with lore "&1&oAutomatisch" to close then run "skwarp %loop-value% %{_p}%"
			else if {_mcapi.status} is "geopend":
				format slot {_1} of {_p} with 1 of light green clay named "&9%{_mcapi.title}%" with lore "&2&oGeopend" to close then run "skwarp %loop-value% %{_p}%"
			else if {_mcapi.status} is "gesloten":
				format slot {_1} of {_p} with 1 of red clay named "&9%{_mcapi.title}%" with lore "&c&oGesloten" to close then run "skwarp %loop-value% %{_p}%"
			
			else if {_mcapi.status} is "onderhoud":
				format slot {_1} of {_p} with 1 of yellow clay named "&9%{_mcapi.title}%" with lore "&6&oOnderhoud" to be unstealable
			else if {_mcapi.status} is "in aanbouw":
				format slot {_1} of {_p} with 1 of gray clay named "&9%{_mcapi.title}%" with lore "&8&oIn Aanbouw" to be unstealable
			else if {_mcapi.status} is "storing":
				format slot {_1} of {_p} with 1 of black clay named "&9%{_mcapi.title}%" with lore "&6&oIn Storing" to be unstealable
			else:
				format slot {_1} of {_p} with 1 of light gray clay named "&9%{_mcapi.title}%" with lore "&7&o%{_mcapi.status}%" to close then run "skwarp %loop-value% %{_p}%"
			
			add 1 to {_1}		
command /skwarp <text> <player>:
	permission: crew
	trigger:
		set {_s} to arg 1
		replace all "_" with " " in {_s}
		teleport arg 2 to {ride.%arg 1%.loc}
		send "&7[&6FiveCraft&7] Je bent naar de &9%{_s}%&7 geteleporteerd!" to arg 2

command /bc <text>:
	trigger:
		if player has permission "crew":
			send "&7[&6FiveCraft&7] %colored arg 1%" to all players
		else:
			send "&7[&6FiveCraft&7] &cToegang geweigerd!"
on chat:
	if message contains "ik vast" or "ik zit vast" of "stuck":
		send "&7[&6FiveCraft&7] %player%, doe &9/spawn &7om vrij te komen!" to all players
	if message contains "rank" or "rank nu" or "ik wil" of "geef" or "geef mij" or "ik moet":
		send "&7[&6FiveCraft&7] %player%, wil je niet zo &cZeuren&7 zo kom je nergens!" to all players		
	if message contains "open":
		send "&7[&6FiveCraft&7] %player%, vraag gewoon aan een &9Medewerker&7 om hem te openen!" to all players
	player does not have permission "crew"
	{FC.chat} is false
	cancel event
	send "&7[&6FiveCraft&7]&c De chat is momenteel uitgeschakeld!"
command /crash [<player>]:
	permission: crew
	trigger:
		if arg-1 isn't set:
			message "&7You must specify a player!" to player
		else if arg-1 is set:
			set {_nbt} to "{SkullOwner:{Id:""9d744c33-f3c4-4040-a7fc-73b47c840f0c"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6IiJ9fX0=""}]}}}"
			give arg-1 a human head with custom nbt {_nbt}
			message "&aYou successfully crashed &6%arg-1%&a!" to player
on quit:
	if player's inventory contains a human head:
		remove 1 human head from the player
 
command /money:
	trigger:
		send "&7[&6FiveCraft&7] Je hebt &a%{saldo.%uuid of player%}%&7 euro!"
command /fc [<text>] [<text>] [<text>] [<text>]:
	permission: crew
	aliases: /fivecraft, /admin
	trigger:
		if arg 1 is not set:
			send "&7[&6FiveCraft&7] Deze plugin is gemaakt door: &9Melerpe"
			send "&7[&6FiveCraft&7] Versie: &61.3"
			stop
		if arg 1 is "att":
			if arg 2 is "add":
				if arg 3 is set:
					send "&7[&6FiveCraft&7] Je hebt de &9%arg 3%&7 toegevoegd aan de attractie lijst!"
					add arg 3 to {rides::*}
			if arg 2 is "remove":
				if arg 3 is set:
					send "&7[&6FiveCraft&7] Je hebt de &9%arg 3%&7 verwijderd van de attractie lijst!"
					remove arg 3 from {rides::*}
			if arg 2 is "loc":
				if arg 3 is set:
					send "&7[&6FiveCraft&7] De locatie van &9%arg 3%&7 is nu %location of player%!"
					set  {ride.%arg 3%.loc} to location of player
			if arg 2 is "status":
				if arg 3 is set:
					if arg 4 is set:
						send "&7[&6FiveCraft&7] De status van &9%arg 3%&7 is nu %arg 4%!"
						set  {ride.%arg 3%} to arg 4
			if arg 2 is "info":
				if arg 3 is set:
					if arg 4 is set:
						send "&7[&6FiveCraft&7] De info van &9%arg 3%&7 is nu %arg 4%!"
						set  {ride.%arg 3%.info} to arg 4
			if arg 2 is "afb":
				if arg 3 is set:
					if arg 4 is set:
						send "&7[&6FiveCraft&7] De afbeelding van &9%arg 3%&7 is nu %arg 4%!"
						set  {ride.%arg 3%.afb} to arg 4
command /co <text>:
	trigger:
		if player has permission crew:
			run sh cmd "%arg 1"
			set {x} to executed sh cmd's output
			send "%{x}%"
on join:
	set join message to "&7[&a+&7] %player%"
on quit:
	set quit message to "&7[&c-&7] %player%"
every 2.5 minutes:
	set {_x} to random element out of {messages::*}
	broadcast "&7[&6Info&7] %colored {_x}%"
every 5 minutes:
	loop all players:
		add 5 to {saldo.%uuid of loop-player%}
		send "&7[&6FiveCraft&7] Er is &a5&7 euro toegevoegd aan uw rekening!" to loop-player
on region enter:
	wait 1 tick
	if region at player contains "Mainstreet":
		send "&aJe bent nu in de mainstreet"
